# Generated by Django 3.2.3 on 2021-05-19 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proname', models.CharField(max_length=255)),
                ('minbid', models.DecimalField(decimal_places=10, max_digits=20)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.user')),
            ],
        ),
    ]
