# Generated by Django 3.2.3 on 2021-05-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='minbid',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
